storage:
  type: YAML  # or MYSQL
  mysql:
    host: localhost
    port: 3306
    database: pwingeco
    username: root
    password: password
    pool-size: 10


currencies:
  dollars:
    symbol: "$"
    primary: true
    global: true
  gems:
    symbol: "♦"
    primary: false
    global: false
    enabled-worlds:
      - "world_rpg"
      - "world_mining"

