name: PwingEco
version: 1.1.2
main: com.pwing.pwingeco.PwingEco
api-version: '1.20'
authors:
  - finder17
description: A Minecraft economy plugin
depend: [Vault]
softdepend: [Skript, PlaceholderAPI]

commands:
  currencyadmin:
    description: Admin commands for managing currencies
    usage: /<command> <subcommand> [args]
    permission: admin.pwing.currency
  balance:
    description: Check your currency balance
    aliases: [bal]
    usage: /<command> [currency]
  pay:
    description: Pay another player
    usage: /<command> <player> <amount> <currency>
  balancetop:
    description: View top balances
    aliases: [baltop]
    usage: /<command> [currency]
  pwingeco:
    description: Reload the PwingEco plugin configuration
    usage: /<command> reload
    permission: admin.pwingeco.reload
  pwingecosave:
    description: Save the PwingEco plugin configuration
    usage: /<command> save
    permission: admin.pwingeco.save
  deposititems:
    description: Deposit items as currency
    usage: /<command> <amount> <currency>
  withdrawitems:
    description: Withdraw items as currency
    usage: /<command> <amount> <currency>
permissions:
  admin.pwing.currency:
    description: Allows access to currency admin commands
    default: op
  admin.pwingeco.reload:
    description: Allows reloading of the PwingEco plugin configuration
    default: op
  admin.pwingeco.save:
    description: Allows saving of the PwingEco plugin configuration
    default: op
